package Grupos;

import Conexao_BD.Conexao;
import static Grupos.GruposInsert.rs;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class Alterar_Grupos extends javax.swing.JFrame {
 public static Vector<Vector> dados = new Vector<>();
       private DefaultTableModel Pesquisa;
    private Object[] Linhas;

    Vector registroLido = new Vector();
    java.sql.Statement stmt = Conexao.stmt;
//public static Vector<Vector> dados = new Vector<>();
    public Alterar_Grupos() {
        initComponents();
           Pesquisa = new DefaultTableModel(null, new String[]{" CÓDIGO ", " NOME"});
        jTable1.setModel(Pesquisa);
        try {
            rs = stmt.executeQuery("SELECT * FROM GRUPOS ");
            while (rs.next()) {

                int CODIGO_GRUPO = rs.getInt("CODIGO_GRUPO");
                String NOME_GRUPO = rs.getString("NOME_GRUPO");

                Linhas = new Object[]{CODIGO_GRUPO, NOME_GRUPO};
                Pesquisa.addRow(Linhas);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " O Grupo não Existe! ");
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Alterar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Button_Sair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Entrada_Nome_Grupo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        Carregar_Tabela = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jCheckBox1.setText("jCheckBox1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Grupos");

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Button_Sair.setText("Sair");
        Button_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SairActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Grupo", "Nome Do Grupo"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Obs: Selecione o Grupo que você deseja alterar e clique em \"Alterar\".");

        Entrada_Nome_Grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_Nome_GrupoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do Grupo");

        Search.setText("Pesquisar");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Carregar_Tabela.setText("Carregar Tabela");
        Carregar_Tabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carregar_TabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Entrada_Nome_Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Search))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Alterar)
                        .addGap(18, 18, 18)
                        .addComponent(Carregar_Tabela)
                        .addGap(18, 18, 18)
                        .addComponent(Button_Sair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Entrada_Nome_Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Carregar_Tabela, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Sair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SairActionPerformed
        dispose();
        
    }//GEN-LAST:event_Button_SairActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed

        int LinhaSelecionada = this.jTable1.getSelectedRow();
        String CODIGO_GRUPO = this.jTable1.getValueAt(LinhaSelecionada, 0).toString();
        String NOME_GRUPO = this.jTable1.getValueAt(LinhaSelecionada, 1).toString();
        new Alterar(CODIGO_GRUPO, NOME_GRUPO).setVisible(true);

    }//GEN-LAST:event_AlterarActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed

        
       String Item = Entrada_Nome_Grupo.getText();

        Pesquisa = new DefaultTableModel(null, new String[]{" CÓDIGO ", " NOME"});
        jTable1.setModel(Pesquisa);
        try {
            rs = stmt.executeQuery("SELECT * FROM GRUPOS WHERE NOME_GRUPO LIKE '%" + Item + "%' ");
            while (rs.next()) {
                int CODIGO_GRUPO = rs.getInt("CODIGO_GRUPO");
                String NOME_GRUPO = rs.getString("NOME_GRUPO");

                Linhas = new Object[]{CODIGO_GRUPO, NOME_GRUPO};
                Pesquisa.addRow(Linhas);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " O Grupo não Existe! ");
        }
        
        /*
        GruposInsert Insert = new GruposInsert();
        String Nome = Entrada_Nome_Grupo.getText();
           try {
            rs = stmt.executeQuery("SELECT * FROM GRUPOS WHERE NOME_GRUPO = '" + Nome + "' ");
            while (rs.next()) {
                int CODIGO_GRUPO = rs.getInt("CODIGO_GRUPO");
                String NOME_GRUPO = rs.getString("NOME_GRUPO");
                Vector registroLido = new Vector();
                registroLido.add(CODIGO_GRUPO);
                registroLido.add(NOME_GRUPO);
                dados.add(registroLido);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " ERRO: " + ex);
        }
*/        
        //DefaultTableModel dtm = new DefaultTableModel();
        //     JTable jtable = new JTable(dtm);
       
        /*
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < dados.size(); i++) {
            dtm.addRow(dados.get(i));
       
        }
        */
    }//GEN-LAST:event_SearchActionPerformed
    private void Entrada_Nome_GrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_Nome_GrupoActionPerformed

    }//GEN-LAST:event_Entrada_Nome_GrupoActionPerformed

    private void Carregar_TabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carregar_TabelaActionPerformed

         Pesquisa = new DefaultTableModel(null, new String[]{" CÓDIGO ", " NOME"});
        jTable1.setModel(Pesquisa);
        try {
            rs = stmt.executeQuery("SELECT * FROM GRUPOS ");
            while (rs.next()) {

                int CODIGO_GRUPO = rs.getInt("CODIGO_GRUPO");
                String NOME_GRUPO = rs.getString("NOME_GRUPO");

                Linhas = new Object[]{CODIGO_GRUPO, NOME_GRUPO};
                Pesquisa.addRow(Linhas);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " O Grupo não Existe! ");
        }
        /*
          try {
            rs = stmt.executeQuery("SELECT * FROM GRUPOS ");
            while (rs.next()) {
                int CODIGO_GRUPO = rs.getInt("CODIGO_GRUPO");
                String NOME_GRUPO = rs.getString("NOME_GRUPO");
                Vector registroLido = new Vector();
                registroLido.add(CODIGO_GRUPO);
                registroLido.add(NOME_GRUPO);
                dados.add(registroLido);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " ERRO: " + ex);
        */
/*           DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < dados.size(); i++) {
            dtm.addRow(dados.get(i));
        }
        */
    }//GEN-LAST:event_Carregar_TabelaActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alterar_Grupos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alterar_Grupos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alterar_Grupos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alterar_Grupos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Alterar_Grupos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Button_Sair;
    private javax.swing.JButton Carregar_Tabela;
    private javax.swing.JTextField Entrada_Nome_Grupo;
    private javax.swing.JButton Search;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
