/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Grupos;

import Conexao_BD.Conexao;
import static Grupos.GruposInsert.dados2;
import static Grupos.GruposInsert.rs;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ricardo
 */
public class Excluir_Grupos extends javax.swing.JFrame {

    /**
     * Creates new form Excluir_Grupos
     */
    private DefaultTableModel Pesquisa;
    private Object[] Linhas;

    Vector registroLido = new Vector();
    Statement stmt = Conexao.stmt;

    public Excluir_Grupos() {
        initComponents();

        Pesquisa = new DefaultTableModel(null, new String[]{" CÓDIGO ", " NOME"});
        jTable2.setModel(Pesquisa);
        try {
            rs = stmt.executeQuery("SELECT * FROM GRUPOS ");
            while (rs.next()) {

                int CODIGO_GRUPO = rs.getInt("CODIGO_GRUPO");
                String NOME_GRUPO = rs.getString("NOME_GRUPO");

                Linhas = new Object[]{CODIGO_GRUPO, NOME_GRUPO};
                Pesquisa.addRow(Linhas);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " O Grupo não Existe! ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Entrada_Nome_Grupo = new javax.swing.JTextField();
        Pesquisar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Carregar_Tabela = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Grupo", "Nome Do Grupo"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisar/Excluir ");

        jLabel1.setText("Informe o nome do grupo a ser excluido");

        Entrada_Nome_Grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_Nome_GrupoActionPerformed(evt);
            }
        });

        Pesquisar.setText("Pesquisar");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        Excluir.setForeground(new java.awt.Color(255, 0, 0));
        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.setMaximumSize(new java.awt.Dimension(63, 23));
        Sair.setMinimumSize(new java.awt.Dimension(63, 23));
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Grupo", "Nome Do Grupo"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        Carregar_Tabela.setText("Carregar Tabela");
        Carregar_Tabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carregar_TabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Entrada_Nome_Grupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pesquisar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 248, Short.MAX_VALUE))))
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Carregar_Tabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Entrada_Nome_Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Sair, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Carregar_Tabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed

        String Item = Entrada_Nome_Grupo.getText();

        Pesquisa = new DefaultTableModel(null, new String[]{" CÓDIGO ", " NOME"});
        jTable2.setModel(Pesquisa);
        try {
            rs = stmt.executeQuery("SELECT * FROM GRUPOS WHERE NOME_GRUPO LIKE '%" + Item + "%' ");
            while (rs.next()) {
                int CODIGO_GRUPO = rs.getInt("CODIGO_GRUPO");
                String NOME_GRUPO = rs.getString("NOME_GRUPO");

                Linhas = new Object[]{CODIGO_GRUPO, NOME_GRUPO};
                Pesquisa.addRow(Linhas);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " O Grupo não Existe! ");
        }
    }//GEN-LAST:event_PesquisarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        /*      
         int optionss = 0;
         while (optionss == 0) {  
         */
        int LinhaSelecionada = this.jTable2.getSelectedRow();
                   String CODIGO_GRUPO = this.jTable2.getValueAt(LinhaSelecionada, 0).toString();
        String NOME_GRUPO = this.jTable2.getValueAt(LinhaSelecionada, 1).toString();
        int x = JOptionPane.showConfirmDialog(null, "Deseja Realmente Excluir esse item?");

        if (x == JOptionPane.OK_OPTION) {
            try {
                 /*
                int codigo = Integer.parseInt(Entrada_Codigo.getText());*/
                stmt.executeUpdate("DELETE FROM GRUPOS WHERE CODIGO_GRUPO = '" + CODIGO_GRUPO + "' ");
                JOptionPane.showMessageDialog(null, " Deletado com Sucesso!");

            } catch (java.sql.SQLException e) {
                JOptionPane.showMessageDialog(null, " Erro ao Deletar Grupo!");
            }
        } else {

            JOptionPane.showMessageDialog(null, "Grupo não Excluido! ");
            GruposInsert.rs = null;
        }

        /* Object[] options = { "Sim", "Não" };   
         JOptionPane.showOptionDialog(null, "Rodar o programa de novo?",
         "De novo?", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
         null, options, options[0]);  
         */

      
    }//GEN-LAST:event_ExcluirActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed

        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void Entrada_Nome_GrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_Nome_GrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entrada_Nome_GrupoActionPerformed

    private void Carregar_TabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carregar_TabelaActionPerformed

        Pesquisa = new DefaultTableModel(null, new String[]{" CÓDIGO ", " NOME"});
        jTable2.setModel(Pesquisa);
        try {
            rs = stmt.executeQuery("SELECT * FROM GRUPOS ");
            while (rs.next()) {

                int CODIGO_GRUPO = rs.getInt("CODIGO_GRUPO");
                String NOME_GRUPO = rs.getString("NOME_GRUPO");

                Linhas = new Object[]{CODIGO_GRUPO, NOME_GRUPO};
                Pesquisa.addRow(Linhas);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " O Grupo não Existe! ");
        }

    }//GEN-LAST:event_Carregar_TabelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Excluir_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Excluir_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Excluir_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Excluir_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Excluir_Grupos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carregar_Tabela;
    private javax.swing.JTextField Entrada_Nome_Grupo;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
