/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Materiais;
import Conexao_BD.Conexao;
import static Materiais.MaterialInsert.rs;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ricardo
 */
public class Alterar_Materiais extends javax.swing.JFrame {

    /**
     * Creates new form Alterar_Materiais
     */
    
    private DefaultTableModel Pesquisa;
    private Object[] Linhas;
    Statement stmt = Conexao.stmt;

    
    public Alterar_Materiais() {
        initComponents();
        
         Pesquisa = new DefaultTableModel(null, new String[]{"CODIGO_MATERIAL","NOME_MATERIAL",
              "CODIGO_GRUPO","UNIDADE","CODIGO_DE_BARRAS","VALOR","CODIGO_FORNECEDOR"});
        jTable1.setModel(Pesquisa);
            try {
         rs = stmt.executeQuery("SELECT * FROM MATERIAIS ;");
            while (rs.next()) {

                int CODIGO_MATERIAL = rs.getInt("CODIGO_MATERIAL");
                String NOME_MATERIAL = rs.getString("NOME_MATERIAL");
                String CODIGO_GRUPO = rs.getString("CODIGO_GRUPO");
                String UNIDADE = rs.getString("UNIDADE");
                String CODIGO_DE_BARRAS = rs.getString("CODIGO_DE_BARRAS");
                String VALOR = rs.getString("VALOR");
                String CODIGO_FORNECEDOR = rs.getString("CODIGO_FORNECEDOR");
                
                Linhas = new Object[]{CODIGO_MATERIAL,NOME_MATERIAL,CODIGO_GRUPO,
                    UNIDADE,CODIGO_DE_BARRAS,VALOR,CODIGO_FORNECEDOR};
                Pesquisa.addRow(Linhas);
            }    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " ERRO: " + ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Busca = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Entrada_Nome_Material = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Pesquisar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Alterar = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        CarregarTabela = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Material");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Informe Nome do Material a ser Alterado");

        Pesquisar.setText("Pesquisar");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Entrada_Nome_Material, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pesquisar))
                    .addComponent(jLabel1))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Entrada_Nome_Material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOME ", "GRUPO", "UNIDADE", "COD. BARRAS", "VALOR", "FORNECEDOR"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        CarregarTabela.setText("Carregar Tabela");
        CarregarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarTabelaActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Obs: Selecione o Grupo que você deseja alterar e clique em \"Alterar\".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Alterar)
                .addGap(18, 18, 18)
                .addComponent(CarregarTabela)
                .addGap(18, 18, 18)
                .addComponent(Sair)
                .addGap(222, 222, 222))
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CarregarTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        // TODO add your handling code here:
        
        
        String nome = Entrada_Nome_Material.getText();
          Pesquisa = new DefaultTableModel(null, new String[]{"CODIGO_MATERIAL","NOME_MATERIAL",
              "CODIGO_GRUPO","UNIDADE","CODIGO_DE_BARRAS","VALOR","CODIGO_FORNECEDOR"});
        jTable1.setModel(Pesquisa);
            try {
         rs = stmt.executeQuery("SELECT * FROM MATERIAIS WHERE NOME_MATERIAL = '"+nome+"';");
            while (rs.next()) {

                int CODIGO_MATERIAL = rs.getInt("CODIGO_MATERIAL");
                String NOME_MATERIAL = rs.getString("NOME_MATERIAL");
                String CODIGO_GRUPO = rs.getString("CODIGO_GRUPO");
                String UNIDADE = rs.getString("UNIDADE");
                String CODIGO_DE_BARRAS = rs.getString("CODIGO_DE_BARRAS");
                String VALOR = rs.getString("VALOR");
                String CODIGO_FORNECEDOR = rs.getString("CODIGO_FORNECEDOR");
                Linhas = new Object[]{CODIGO_MATERIAL,NOME_MATERIAL,CODIGO_GRUPO,
                    UNIDADE,CODIGO_DE_BARRAS,VALOR,CODIGO_FORNECEDOR};
                Pesquisa.addRow(Linhas);
            }    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " ERRO: " + ex);
        }
    }//GEN-LAST:event_PesquisarActionPerformed

    private void CarregarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregarTabelaActionPerformed
        // TODO add your handling code here:
         Pesquisa = new DefaultTableModel(null, new String[]{"CODIGO_MATERIAL","NOME_MATERIAL",
              "CODIGO_GRUPO","UNIDADE","CODIGO_DE_BARRAS","VALOR","CODIGO_FORNECEDOR"});
        jTable1.setModel(Pesquisa);
            try {
         rs = stmt.executeQuery("SELECT * FROM MATERIAIS ;");
            while (rs.next()) {

                int CODIGO_MATERIAL = rs.getInt("CODIGO_MATERIAL");
                String NOME_MATERIAL = rs.getString("NOME_MATERIAL");
                String CODIGO_GRUPO = rs.getString("CODIGO_GRUPO");
                String UNIDADE = rs.getString("UNIDADE");
                String CODIGO_DE_BARRAS = rs.getString("CODIGO_DE_BARRAS");
                String VALOR = rs.getString("VALOR");
                String CODIGO_FORNECEDOR = rs.getString("CODIGO_FORNECEDOR");
                
                Linhas = new Object[]{CODIGO_MATERIAL,NOME_MATERIAL,CODIGO_GRUPO,
                    UNIDADE,CODIGO_DE_BARRAS,VALOR,CODIGO_FORNECEDOR};
                Pesquisa.addRow(Linhas);
            }    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " ERRO: " + ex);
        }
        
    }//GEN-LAST:event_CarregarTabelaActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        // TODO add your handling code here:
        
        int LinhaSelecionada = this.jTable1.getSelectedRow();
        String CODIGO_MATERIAL = this.jTable1.getValueAt(LinhaSelecionada, 0).toString();
        String NOME_MATERIAL = this.jTable1.getValueAt(LinhaSelecionada, 1).toString();
        String CODIGO_GRUPO = this.jTable1.getValueAt(LinhaSelecionada, 2).toString();
        String UNIDADE = this.jTable1.getValueAt(LinhaSelecionada, 3).toString();
        String CODIGO_DE_BARRAS = this.jTable1.getValueAt(LinhaSelecionada, 4).toString();
        String VALOR = this.jTable1.getValueAt(LinhaSelecionada, 5).toString();
        String CODIGO_FORNECEDOR = this.jTable1.getValueAt(LinhaSelecionada, 6).toString();
        
        new Alterar(
                CODIGO_MATERIAL, NOME_MATERIAL, CODIGO_GRUPO,
                UNIDADE, CODIGO_DE_BARRAS, VALOR, CODIGO_FORNECEDOR 
        ).setVisible(true);   
        
        
    }//GEN-LAST:event_AlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alterar_Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alterar_Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alterar_Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alterar_Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Alterar_Materiais().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.ButtonGroup Busca;
    private javax.swing.JButton CarregarTabela;
    private javax.swing.JTextField Entrada_Nome_Material;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
