/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Materiais;


import Conexao_BD.Conexao;
import static Conexao_BD.Conexao.stmt;
import com.mysql.jdbc.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo
 */
public class Incluir_Materiais extends javax.swing.JFrame {

    int CodG;
    int CodF;
Statement stmt = (Statement) Conexao.stmt;
    public Incluir_Materiais() {
        initComponents();
        try{
            
            ResultSet rsG = stmt.executeQuery("SELECT CODIGO_GRUPO,NOME_GRUPO FROM GRUPOS");
            while(rsG.next()){
                Lista_Nome_Grupo.addItem(rsG.getString("NOME_GRUPO"));
                CodG = (rsG.getInt("CODIGO_GRUPO"));
            }
                
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"ERRO"+ex);
        }
        try{
            ResultSet rsF = stmt.executeQuery("SELECT CODIGO_FORNECEDOR,NOME_FORNECEDOR FROM FORNECEDOR");
            while(rsF.next()){
                Lista_Nome_Fornecedor.addItem(rsF.getString("NOME_FORNECEDOR"));
                CodF = (rsF.getInt("CODIGO_FORNECEDOR"));
            }
        }catch(SQLException ez){
            JOptionPane.showMessageDialog(null,"Erro"+ez);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Entrada_unidade = new javax.swing.JTextField();
        Unidade = new javax.swing.JLabel();
        Cod_Barra = new javax.swing.JLabel();
        Entrada_Codigo_Barras = new javax.swing.JTextField();
        Num_Fabricante = new javax.swing.JLabel();
        Valor = new javax.swing.JLabel();
        Entrada_de_Valor = new javax.swing.JTextField();
        Entrada_Nome_Material = new javax.swing.JTextField();
        Label_Nome_Material = new javax.swing.JLabel();
        Nome_Grupo = new javax.swing.JLabel();
        Lista_Nome_Fornecedor = new javax.swing.JComboBox();
        Lista_Nome_Grupo = new javax.swing.JComboBox();
        Ok = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Materiais");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Entrada_unidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_unidadeActionPerformed(evt);
            }
        });

        Unidade.setText("Unidade");

        Cod_Barra.setText("Cod. Barra");

        Entrada_Codigo_Barras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_Codigo_BarrasActionPerformed(evt);
            }
        });

        Num_Fabricante.setText("Nome do Fornecedor");

        Valor.setText("Valor");

        Entrada_de_Valor.setText(" ");
        Entrada_de_Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_de_ValorActionPerformed(evt);
            }
        });

        Entrada_Nome_Material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_Nome_MaterialActionPerformed(evt);
            }
        });

        Label_Nome_Material.setText("Nome do Material");

        Nome_Grupo.setText("Nome do Grupo");

        Lista_Nome_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lista_Nome_FornecedorActionPerformed(evt);
            }
        });

        Lista_Nome_Grupo.setToolTipText("");
        Lista_Nome_Grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lista_Nome_GrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Entrada_Nome_Material)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Label_Nome_Material)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Lista_Nome_Fornecedor, javax.swing.GroupLayout.Alignment.LEADING, 0, 244, Short.MAX_VALUE)
                            .addComponent(Entrada_Codigo_Barras, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cod_Barra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Num_Fabricante, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nome_Grupo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lista_Nome_Grupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Unidade)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Entrada_unidade)
                                .addComponent(Valor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Entrada_de_Valor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Label_Nome_Material)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Entrada_Nome_Material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Entrada_unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Unidade)
                            .addComponent(Nome_Grupo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lista_Nome_Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cod_Barra)
                    .addComponent(Valor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Entrada_Codigo_Barras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Entrada_de_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Num_Fabricante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lista_Nome_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        Ok.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Ok.setText("Ok");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        Cancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cancelar.setText("Desfazer");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Sair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(Ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ok, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Entrada_Nome_MaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_Nome_MaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entrada_Nome_MaterialActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // ação cancelar
        Entrada_Nome_Material.setText("");
        Entrada_unidade.setText("");
        Entrada_Codigo_Barras.setText("");
        Entrada_de_Valor.setText("");

    }//GEN-LAST:event_CancelarActionPerformed

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        //pegar do campo de texto
        
        String Nome = Entrada_Nome_Material.getText();
        String Unidade = Entrada_unidade.getText();
        String Valor = Entrada_de_Valor.getText();
        String CodigoBarras = Entrada_Codigo_Barras.getText();
        

        if ((Entrada_Nome_Material.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
        } else {
// instanciando a classe MaterialInsert do pacote Insert e criando seu objeto Insert
            MaterialInsert Insert = new MaterialInsert();
            Insert.adiciona(Nome, Unidade, CodG, Valor, CodigoBarras, CodF);
            
        }
// apaga os dados preenchidos nos campos de texto

        Entrada_Nome_Material.setText("");
        Entrada_unidade.setText("");
        Entrada_Codigo_Barras.setText("");
        Entrada_de_Valor.setText("");


    }//GEN-LAST:event_OkActionPerformed

    private void Entrada_unidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_unidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entrada_unidadeActionPerformed

    private void Entrada_Codigo_BarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_Codigo_BarrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entrada_Codigo_BarrasActionPerformed

    private void Entrada_de_ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_de_ValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entrada_de_ValorActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void Lista_Nome_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista_Nome_FornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lista_Nome_FornecedorActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed

        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void Lista_Nome_GrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista_Nome_GrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lista_Nome_GrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Incluir_Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Incluir_Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Incluir_Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Incluir_Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Incluir_Materiais().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Cod_Barra;
    private javax.swing.JTextField Entrada_Codigo_Barras;
    private javax.swing.JTextField Entrada_Nome_Material;
    private javax.swing.JTextField Entrada_de_Valor;
    private javax.swing.JTextField Entrada_unidade;
    private javax.swing.JLabel Label_Nome_Material;
    private javax.swing.JComboBox Lista_Nome_Fornecedor;
    private javax.swing.JComboBox Lista_Nome_Grupo;
    private javax.swing.JLabel Nome_Grupo;
    private javax.swing.JLabel Num_Fabricante;
    private javax.swing.JButton Ok;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel Unidade;
    private javax.swing.JLabel Valor;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
