package Main;
import CentroDeCusto.Alterar_CentroDeCusto;
import CentroDeCusto.Excluir_CentroDeCusto;
import CentroDeCusto.Incluir_CentroDeCusto;
import Fornecedor.Alterar_Fornecedor;
import Fornecedor.Excluir_Fornecedor;
import Fornecedor.Incluir_Fornecedor;
import Grupos.Alterar_Grupos;
import Grupos.Excluir_Grupos;
import Grupos.Incluir_Grupos;
import Materiais.Alterar_Materiais;
import Materiais.Excluir_Materiais;
import Materiais.Incluir_Materiais;
import Utilitarios.Data;
import Conexao_BD.Conexao;
import Relatorios.Relacao_Fornecedor;
import Relatorios.Relacao_Grupos;
import Relatorios.Relacao_Materiais;
import Sistemaa.Chave_do_Produto;
import Sistemaa.Sobre;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
//import java.util.GregorianCalendar;
import javax.swing.SwingUtilities;
import javax.swing.*;
public class Tela_Principal extends javax.swing.JFrame {

    Conexao conect;
    Data mostra_Data;
    String seta_Look = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
    /**
     * Creates new form Tela_Principal
     */
    public  Tela_Principal() {
        initComponents();
    
        Main obj = new Main();
        obj.conect();
        
        mostra_Data = new Data() ;
        mostra_Data.Le_Data();
        label_data.setText(" "+mostra_Data.dia+", "+mostra_Data.dia_semana+" de "+mostra_Data.mes+" de "+mostra_Data.ano);
     //   GregorianCalendar gc = new GregorianCalendar() ;
     //   label_data.setText("Data: "+gc.get(GregorianCalendar.DATE)+"/"+gc.get(GregorianCalendar.MONTH)+"/"+gc.get(GregorianCalendar.YEAR));
        mostra_Data.le_hora();
        label_hora.setText("Hora Atual "+mostra_Data.hora);
   
       /* timer2.start();
       */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jFileChooser2 = new javax.swing.JFileChooser();
        Area_Data_Hora = new javax.swing.JPanel();
        label_hora = new java.awt.Label();
        label_data = new java.awt.Label();
        jSeparator15 = new javax.swing.JSeparator();
        Separador1 = new javax.swing.JSeparator();
        Separador2 = new javax.swing.JSeparator();
        Separador3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        Barra_Tarefas = new javax.swing.JMenuBar();
        Cadastros = new javax.swing.JMenu();
        Cad_Grupos = new javax.swing.JMenu();
        Incluir_Grupos = new javax.swing.JMenuItem();
        Alterar_Grupos = new javax.swing.JMenuItem();
        Excluir_Grupos = new javax.swing.JMenuItem();
        Cad_Materiais = new javax.swing.JMenu();
        Incluir_Materiais = new javax.swing.JMenuItem();
        Alterar_Materiais = new javax.swing.JMenuItem();
        Excluir_Materiais = new javax.swing.JMenuItem();
        Cad_Fornecedores = new javax.swing.JMenu();
        Incluir_Fornecedor = new javax.swing.JMenuItem();
        Alterar_Fornecedor = new javax.swing.JMenuItem();
        Excluir_Fornecedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Sair = new javax.swing.JMenuItem();
        Relatórios = new javax.swing.JMenu();
        relacao_grupos = new javax.swing.JMenuItem();
        relacao_materiais = new javax.swing.JMenuItem();
        relacao_fornecedores = new javax.swing.JMenuItem();
        Sistema = new javax.swing.JMenu();
        Sobre = new javax.swing.JMenuItem();
        Chave_Registro = new javax.swing.JMenuItem();
        Aparencias = new javax.swing.JMenu();
        MotifLookAndFeel = new javax.swing.JMenuItem();
        MetalLookAndFeel = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jSeparator10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ESTOCKAGE");

        label_hora.setText("Hora.:");

        label_data.setText("Data.:");

        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout Area_Data_HoraLayout = new javax.swing.GroupLayout(Area_Data_Hora);
        Area_Data_Hora.setLayout(Area_Data_HoraLayout);
        Area_Data_HoraLayout.setHorizontalGroup(
            Area_Data_HoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Area_Data_HoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Area_Data_HoraLayout.setVerticalGroup(
            Area_Data_HoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Area_Data_HoraLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(Area_Data_HoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Area_Data_HoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator15)
                        .addComponent(label_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Estockage_Digital2.jpg"))); // NOI18N

        Cadastros.setMnemonic('C');
        Cadastros.setText("Cadastros");
        Cadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrosActionPerformed(evt);
            }
        });

        Cad_Grupos.setMnemonic('C');
        Cad_Grupos.setText("Grupos");

        Incluir_Grupos.setMnemonic('I');
        Incluir_Grupos.setText("Incluir");
        Incluir_Grupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Incluir_GruposActionPerformed(evt);
            }
        });
        Cad_Grupos.add(Incluir_Grupos);

        Alterar_Grupos.setMnemonic('e');
        Alterar_Grupos.setText("Alterar ");
        Alterar_Grupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alterar_GruposActionPerformed(evt);
            }
        });
        Cad_Grupos.add(Alterar_Grupos);

        Excluir_Grupos.setMnemonic('x');
        Excluir_Grupos.setText("Pesquisar/Excluir");
        Excluir_Grupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir_GruposActionPerformed(evt);
            }
        });
        Cad_Grupos.add(Excluir_Grupos);

        Cadastros.add(Cad_Grupos);

        Cad_Materiais.setMnemonic('a');
        Cad_Materiais.setText("Materiais");

        Incluir_Materiais.setMnemonic('I');
        Incluir_Materiais.setText("Incluir");
        Incluir_Materiais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Incluir_MateriaisActionPerformed(evt);
            }
        });
        Cad_Materiais.add(Incluir_Materiais);

        Alterar_Materiais.setMnemonic('t');
        Alterar_Materiais.setText("Alterar ");
        Alterar_Materiais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alterar_MateriaisActionPerformed(evt);
            }
        });
        Cad_Materiais.add(Alterar_Materiais);

        Excluir_Materiais.setMnemonic('x');
        Excluir_Materiais.setText("Pesquisa/Excluir ");
        Excluir_Materiais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir_MateriaisActionPerformed(evt);
            }
        });
        Cad_Materiais.add(Excluir_Materiais);

        Cadastros.add(Cad_Materiais);

        Cad_Fornecedores.setMnemonic('r');
        Cad_Fornecedores.setText("Fornecedores");

        Incluir_Fornecedor.setMnemonic('I');
        Incluir_Fornecedor.setText("Incluir");
        Incluir_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Incluir_FornecedorActionPerformed(evt);
            }
        });
        Cad_Fornecedores.add(Incluir_Fornecedor);

        Alterar_Fornecedor.setMnemonic('t');
        Alterar_Fornecedor.setText("Alterar");
        Alterar_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alterar_FornecedorActionPerformed(evt);
            }
        });
        Cad_Fornecedores.add(Alterar_Fornecedor);

        Excluir_Fornecedor.setMnemonic('x');
        Excluir_Fornecedor.setText("Pesquisar/Excluir");
        Excluir_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir_FornecedorActionPerformed(evt);
            }
        });
        Cad_Fornecedores.add(Excluir_Fornecedor);

        Cadastros.add(Cad_Fornecedores);
        Cadastros.add(jSeparator1);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Cadastros.add(Sair);

        Barra_Tarefas.add(Cadastros);

        Relatórios.setMnemonic('R');
        Relatórios.setText("Relatórios");

        relacao_grupos.setMnemonic('G');
        relacao_grupos.setText("Relação dos Grupos");
        relacao_grupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacao_gruposActionPerformed(evt);
            }
        });
        Relatórios.add(relacao_grupos);

        relacao_materiais.setMnemonic('R');
        relacao_materiais.setText("Relação de Materiais");
        relacao_materiais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacao_materiaisActionPerformed(evt);
            }
        });
        Relatórios.add(relacao_materiais);

        relacao_fornecedores.setMnemonic('N');
        relacao_fornecedores.setText("Relação dos Fornecedores");
        relacao_fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacao_fornecedoresActionPerformed(evt);
            }
        });
        Relatórios.add(relacao_fornecedores);

        Barra_Tarefas.add(Relatórios);

        Sistema.setMnemonic('S');
        Sistema.setText("Sistema");

        Sobre.setMnemonic('s');
        Sobre.setText("Sobre");
        Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreActionPerformed(evt);
            }
        });
        Sistema.add(Sobre);

        Chave_Registro.setMnemonic('c');
        Chave_Registro.setText("Chave de Registro");
        Chave_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chave_RegistroActionPerformed(evt);
            }
        });
        Sistema.add(Chave_Registro);

        Aparencias.setText("Aparências");

        MotifLookAndFeel.setText("MotifLookAndFeel");
        MotifLookAndFeel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotifLookAndFeelActionPerformed(evt);
            }
        });
        Aparencias.add(MotifLookAndFeel);

        MetalLookAndFeel.setText("MetalLookAndFeel");
        MetalLookAndFeel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetalLookAndFeelActionPerformed(evt);
            }
        });
        Aparencias.add(MetalLookAndFeel);

        jMenuItem4.setText("WindowLookAndFeel");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Aparencias.add(jMenuItem4);

        Sistema.add(Aparencias);

        Barra_Tarefas.add(Sistema);

        setJMenuBar(Barra_Tarefas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Separador1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Separador3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Area_Data_Hora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Area_Data_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Incluir_GruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Incluir_GruposActionPerformed
        new Incluir_Grupos().setVisible(true);
    }//GEN-LAST:event_Incluir_GruposActionPerformed

    private void Chave_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chave_RegistroActionPerformed
        // TODO add your handling code here:
        new Chave_do_Produto().show();
    }//GEN-LAST:event_Chave_RegistroActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void timer2OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer2OnTime
        // TODO add your handling code here:
        mostra_Data.le_hora();
        label_hora.setText("Hora.: "+mostra_Data.hora);
      
    }//GEN-LAST:event_timer2OnTime

    private void MotifLookAndFeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotifLookAndFeelActionPerformed
        // TODO add your handling code here:
        seta_Look = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
        lookAndFeel();
    }//GEN-LAST:event_MotifLookAndFeelActionPerformed

    private void MetalLookAndFeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetalLookAndFeelActionPerformed
        // TODO add your handling code here:
        seta_Look = "javax.swing.plaf.metal.MetalLookAndFeel";
        lookAndFeel();
    }//GEN-LAST:event_MetalLookAndFeelActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        seta_Look = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
        lookAndFeel();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void Alterar_GruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alterar_GruposActionPerformed
        // TODO add your handling code here:
        new Alterar_Grupos().show();
    }//GEN-LAST:event_Alterar_GruposActionPerformed

    private void Excluir_GruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir_GruposActionPerformed
        // TODO add your handling code here:
        new Excluir_Grupos().show();
    }//GEN-LAST:event_Excluir_GruposActionPerformed

    private void CadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrosActionPerformed

    private void Incluir_MateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Incluir_MateriaisActionPerformed
        // TODO add your handling code here:
        new Incluir_Materiais().show();
    }//GEN-LAST:event_Incluir_MateriaisActionPerformed

    private void Alterar_MateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alterar_MateriaisActionPerformed
        // TODO add your handling code here:
        new Alterar_Materiais().show();
    }//GEN-LAST:event_Alterar_MateriaisActionPerformed

    private void Excluir_MateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir_MateriaisActionPerformed
        // TODO add your handling code here:
        new Excluir_Materiais().show();
    }//GEN-LAST:event_Excluir_MateriaisActionPerformed

    private void Incluir_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Incluir_FornecedorActionPerformed
        // TODO add your handling code here:
        new Incluir_Fornecedor().show();
    }//GEN-LAST:event_Incluir_FornecedorActionPerformed

    private void Alterar_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alterar_FornecedorActionPerformed
        // TODO add your handling code here:
        new Alterar_Fornecedor().show();
    }//GEN-LAST:event_Alterar_FornecedorActionPerformed

    private void Excluir_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir_FornecedorActionPerformed
        // TODO add your handling code here:
        new Excluir_Fornecedor().show();
    }//GEN-LAST:event_Excluir_FornecedorActionPerformed

    private void SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreActionPerformed
        // TODO add your handling code here:
        new Sobre().show();
    }//GEN-LAST:event_SobreActionPerformed

    private void relacao_gruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacao_gruposActionPerformed
        // TODO add your handling code here:
        new Relacao_Grupos().show();
    }//GEN-LAST:event_relacao_gruposActionPerformed

    private void relacao_materiaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacao_materiaisActionPerformed
        // TODO add your handling code here:
        new Relacao_Materiais().show();
    }//GEN-LAST:event_relacao_materiaisActionPerformed

    private void relacao_fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacao_fornecedoresActionPerformed
        // TODO add your handling code here:
        new Relacao_Fornecedor().show();
    }//GEN-LAST:event_relacao_fornecedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Alterar_Fornecedor;
    private javax.swing.JMenuItem Alterar_Grupos;
    private javax.swing.JMenuItem Alterar_Materiais;
    private javax.swing.JMenu Aparencias;
    private javax.swing.JPanel Area_Data_Hora;
    private javax.swing.JMenuBar Barra_Tarefas;
    private javax.swing.JMenu Cad_Fornecedores;
    private javax.swing.JMenu Cad_Grupos;
    private javax.swing.JMenu Cad_Materiais;
    private javax.swing.JMenu Cadastros;
    private javax.swing.JMenuItem Chave_Registro;
    private javax.swing.JMenuItem Excluir_Fornecedor;
    private javax.swing.JMenuItem Excluir_Grupos;
    private javax.swing.JMenuItem Excluir_Materiais;
    private javax.swing.JMenuItem Incluir_Fornecedor;
    private javax.swing.JMenuItem Incluir_Grupos;
    private javax.swing.JMenuItem Incluir_Materiais;
    private javax.swing.JMenuItem MetalLookAndFeel;
    private javax.swing.JMenuItem MotifLookAndFeel;
    private javax.swing.JMenu Relatórios;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JSeparator Separador2;
    private javax.swing.JSeparator Separador3;
    private javax.swing.JMenu Sistema;
    private javax.swing.JMenuItem Sobre;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator15;
    private java.awt.Label label_data;
    private java.awt.Label label_hora;
    private javax.swing.JMenuItem relacao_fornecedores;
    private javax.swing.JMenuItem relacao_grupos;
    private javax.swing.JMenuItem relacao_materiais;
    // End of variables declaration//GEN-END:variables

    public void lookAndFeel(){
        try{
            UIManager.setLookAndFeel(seta_Look);
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
            //UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
           //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        }
    catch(Exception erro)
    {
        JOptionPane.showMessageDialog(null,erro);
    } 
    }

}
