/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Fornecedor;
import Grupos.*;
import Conexao_BD.Conexao;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ricardo
 */
public class Alterar extends javax.swing.JFrame {
    /**
     * Creates new form Alterar
     */
    /*
    String NOME_FORNECEDOR;
    String RAZAO_SOCIAL;
    String NOME_CONTATO;
    String INSCRICAO_ESTADUAL;
    String CNPJ;
    String TELEFONE_1;
    String TELEFONE_2;
    String FAX;
    String ENDERECO;
    String BAIRRO;
    String CEP;
    String CIDADE;
    String UF;
    String PONTO_REFERENCIA;
    String EMAIL;
    String OBSERVACAO;*/
    String CODIGO_FORNECEDOR;
    Statement stmt = Conexao.stmt;
public Alterar(String NOME_FORNECEDOR, String RAZAO_SOCIAL, String NOME_CONTATO,
            String INSCRICAO_ESTADUAL, String CNPJ, String TELEFONE_1, String TELEFONE_2,
            String FAX, String ENDERECO, String BAIRRO,String CEP,String CIDADE, String UF, String PONTO_REFERENCIA, 
            String EMAIL, String OBSERVACAO, String CODIGO_FORNECEDOR) {
            initComponents();
    /*  this.NOME_FORNECEDOR = NOME_FORNECEDOR;
        this.RAZAO_SOCIAL = RAZAO_SOCIAL;
        this.NOME_CONTATO = NOME_CONTATO;
        this.INSCRICAO_ESTADUAL = INSCRICAO_ESTADUAL;
        this.CNPJ = CNPJ;
        this.TELEFONE_1 = TELEFONE_1;
        this.TELEFONE_2 = TELEFONE_2;
        this.FAX = FAX;
        this.ENDERECO = ENDERECO;
        this.BAIRRO = BAIRRO;
        this.CEP = CEP;
        this.CIDADE = CIDADE;
        this.UF = UF;
        this.PONTO_REFERENCIA = PONTO_REFERENCIA;
        this.EMAIL = EMAIL;
        this.OBSERVACAO = OBSERVACAO; */
        this.CODIGO_FORNECEDOR = CODIGO_FORNECEDOR;
        
        this.EntradaFornecedor.setText(NOME_FORNECEDOR);
        this.EntradaRazao.setText(RAZAO_SOCIAL);
        this.EntradaNomeContato.setText(NOME_CONTATO);
        this.EntradaInscricao.setText(INSCRICAO_ESTADUAL);
        this.EntradaCNPJ.setText(CNPJ);
        this.EntradaTelefone1.setText(TELEFONE_1);
        this.EntradaTelefone2.setText(TELEFONE_2);
        this.EntradaFax.setText(FAX);
        this.EntradaEndereco.setText(ENDERECO);
        this.EntradaBairro.setText(BAIRRO);
        this.EntradaCEP.setText(CEP);
        this.EntradaCidade.setText(CIDADE);
        this.EntradaUF.setText(UF);
        this.EntradaPontoRef.setText(PONTO_REFERENCIA);
        this.EntradaEmail.setText(EMAIL);
        this.EntradaObs.setText(OBSERVACAO);       
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sair = new javax.swing.JPanel();
        EntradaFornecedor = new java.awt.TextField();
        EntradaRazao = new java.awt.TextField();
        EntradaNomeContato = new java.awt.TextField();
        EntradaCNPJ = new java.awt.TextField();
        EntradaFax = new java.awt.TextField();
        EntradaTelefone2 = new java.awt.TextField();
        EntradaTelefone1 = new java.awt.TextField();
        Fornecedor = new java.awt.Label();
        RazaoSocial = new java.awt.Label();
        NomeContato = new java.awt.Label();
        InscricaoEstadual = new java.awt.Label();
        Cnpj = new java.awt.Label();
        Telefone1 = new java.awt.Label();
        Telefone2 = new java.awt.Label();
        Fax = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        EntradaBairro = new java.awt.TextField();
        EntradaCEP = new java.awt.TextField();
        Endereco = new java.awt.Label();
        Bairro = new java.awt.Label();
        Cep = new java.awt.Label();
        EntradaCidade = new java.awt.TextField();
        EntradaUF = new java.awt.TextField();
        EntradaPontoRef = new java.awt.TextField();
        Cidade = new java.awt.Label();
        UF = new java.awt.Label();
        PontoRef = new java.awt.Label();
        EntradaEmail = new java.awt.TextField();
        EntradaObs = new java.awt.TextArea();
        Obs = new java.awt.Label();
        Email = new java.awt.Label();
        EntradaEndereco = new java.awt.TextField();
        EntradaInscricao = new java.awt.TextField();
        Alterar = new javax.swing.JButton();
        Desfazer = new javax.swing.JButton();
        sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Fornecedor");

        Sair.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        EntradaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaFornecedorActionPerformed(evt);
            }
        });
        EntradaFornecedor.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                EntradaFornecedorInputMethodTextChanged(evt);
            }
        });

        EntradaRazao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaRazaoActionPerformed(evt);
            }
        });

        EntradaNomeContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaNomeContatoActionPerformed(evt);
            }
        });

        EntradaCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaCNPJActionPerformed(evt);
            }
        });

        EntradaFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaFaxActionPerformed(evt);
            }
        });

        EntradaTelefone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaTelefone2ActionPerformed(evt);
            }
        });

        EntradaTelefone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaTelefone1ActionPerformed(evt);
            }
        });

        Fornecedor.setText("Fornecedor*");

        RazaoSocial.setText("Razão Social*");

        NomeContato.setText("Nome do Contato");

        InscricaoEstadual.setText("Inscrição Estadual*");

        Cnpj.setText("CNPJ*");

        Telefone1.setText("Telefone 1*");

        Telefone2.setText("Telefone 2");

        Fax.setText("FAX");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        EntradaBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaBairroActionPerformed(evt);
            }
        });

        EntradaCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaCEPActionPerformed(evt);
            }
        });

        Endereco.setText("Endereço*");

        Bairro.setText("Bairro*");

        Cep.setText("CEP*");

        EntradaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaCidadeActionPerformed(evt);
            }
        });

        EntradaUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaUFActionPerformed(evt);
            }
        });

        Cidade.setText("Cidade*");

        UF.setText("UF*");

        PontoRef.setText("Ponto de Referência");

        EntradaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaEmailActionPerformed(evt);
            }
        });

        Obs.setText("Observações");

        Email.setText("E-mail*");

        EntradaEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntradaCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntradaEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EntradaEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EntradaObs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntradaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntradaCEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 74, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EntradaUF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addComponent(EntradaPontoRef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Obs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PontoRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(EntradaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(EntradaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(EntradaCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(EntradaUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addComponent(PontoRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(EntradaPontoRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(EntradaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(EntradaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Obs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(EntradaObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EntradaInscricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaInscricaoActionPerformed(evt);
            }
        });

        Alterar.setText("Alterar");
        Alterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlterarMouseClicked(evt);
            }
        });
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Desfazer.setText("Desfazer");
        Desfazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesfazerActionPerformed(evt);
            }
        });

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SairLayout = new javax.swing.GroupLayout(Sair);
        Sair.setLayout(SairLayout);
        SairLayout.setHorizontalGroup(
            SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SairLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SairLayout.createSequentialGroup()
                        .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SairLayout.createSequentialGroup()
                                .addComponent(Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(EntradaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SairLayout.createSequentialGroup()
                                .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SairLayout.createSequentialGroup()
                                        .addComponent(NomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20))
                                    .addGroup(SairLayout.createSequentialGroup()
                                        .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(InscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EntradaRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EntradaNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EntradaInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EntradaCNPJ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EntradaTelefone2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EntradaFax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EntradaTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SairLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Alterar)
                .addGap(26, 26, 26)
                .addComponent(Desfazer)
                .addGap(28, 28, 28)
                .addComponent(sair)
                .addGap(239, 239, 239))
        );
        SairLayout.setVerticalGroup(
            SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SairLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SairLayout.createSequentialGroup()
                        .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EntradaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EntradaRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntradaNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EntradaInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SairLayout.createSequentialGroup()
                        .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EntradaTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EntradaTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SairLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(EntradaFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EntradaCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Alterar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(Desfazer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed

        try {
            stmt.executeUpdate("UPDATE FORNECEDOR SET NOME_FORNECEDOR = '" + this.EntradaFornecedor.getText() + "'"
            + ", RAZAO_SOCIAL = '" + this.EntradaRazao.getText() + "', NOME_CONTATO = '" +this.EntradaNomeContato.getText()+ "'"
            + ", INSCRICAO_ESTADUAL = '"+this.EntradaInscricao.getText()+"', CNPJ = '"+this.EntradaCNPJ.getText()+"', TELEFONE1 = '"+EntradaTelefone1.getText()+"'"
            + ", TELEFONE2 = '"+this.EntradaTelefone2.getText()+"', FAX = '"+this.EntradaFax.getText()+"', ENDERECO = '"+this.EntradaEndereco.getText()+"'"
            + ", BAIRRO = '"+this.EntradaBairro.getText()+"', CEP = '"+this.EntradaCEP.getText()+"', CIDADE = '"+this.EntradaCidade.getText()+"'"
            + ", UF = '"+this.EntradaUF.getText()+"', PONTO_REFERENCIA = '"+this.EntradaPontoRef.getText()+"', EMAIL = '"+this.EntradaEmail.getText()+"'"
            + ", OBSERVACAO = '"+this.EntradaObs.getText()+"' WHERE (CODIGO_FORNECEDOR) =  '" + this.CODIGO_FORNECEDOR + "' ;");
           
            JOptionPane.showMessageDialog(null, "Alterado com Sucesso!");
        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(null, " Erro ao Alterar Nome do Grupo!");
        }
        
    }//GEN-LAST:event_AlterarActionPerformed

    private void AlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlterarMouseClicked

    }//GEN-LAST:event_AlterarMouseClicked

    private void EntradaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaFornecedorActionPerformed

    }//GEN-LAST:event_EntradaFornecedorActionPerformed

    private void EntradaFornecedorInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_EntradaFornecedorInputMethodTextChanged

    }//GEN-LAST:event_EntradaFornecedorInputMethodTextChanged

    private void EntradaRazaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaRazaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaRazaoActionPerformed

    private void EntradaNomeContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaNomeContatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaNomeContatoActionPerformed

    private void EntradaCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaCNPJActionPerformed

    private void EntradaFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaFaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaFaxActionPerformed

    private void EntradaTelefone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaTelefone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaTelefone2ActionPerformed

    private void EntradaTelefone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaTelefone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaTelefone1ActionPerformed

    private void EntradaBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaBairroActionPerformed

    private void EntradaCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaCEPActionPerformed

    private void EntradaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaCidadeActionPerformed

    private void EntradaUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaUFActionPerformed

    private void EntradaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaEmailActionPerformed

    private void EntradaEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaEnderecoActionPerformed

    private void EntradaInscricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaInscricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaInscricaoActionPerformed

    private void DesfazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesfazerActionPerformed
        // TODO add your handling code here:
        
        EntradaFornecedor.setText("");
        EntradaRazao.setText("");
        EntradaInscricao.setText("");
        EntradaCNPJ.setText("");
        EntradaTelefone1.setText("");
        EntradaTelefone2.setText("");
        EntradaEndereco.setText("");
        EntradaBairro.setText("");
        EntradaCEP.setText("");
        EntradaCidade.setText("");
        EntradaUF.setText("");
        EntradaEmail.setText("");
        EntradaObs.setText("");
        EntradaNomeContato.setText("");
        EntradaFax.setText("");
        EntradaPontoRef.setText("");
    }//GEN-LAST:event_DesfazerActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_sairActionPerformed
    /**
     * @param args the cEntrada_Novo_Gruponts
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private java.awt.Label Bairro;
    private java.awt.Label Cep;
    private java.awt.Label Cidade;
    private java.awt.Label Cnpj;
    private javax.swing.JButton Desfazer;
    private java.awt.Label Email;
    private java.awt.Label Endereco;
    private java.awt.TextField EntradaBairro;
    private java.awt.TextField EntradaCEP;
    private java.awt.TextField EntradaCNPJ;
    private java.awt.TextField EntradaCidade;
    private java.awt.TextField EntradaEmail;
    private java.awt.TextField EntradaEndereco;
    private java.awt.TextField EntradaFax;
    private java.awt.TextField EntradaFornecedor;
    private java.awt.TextField EntradaInscricao;
    private java.awt.TextField EntradaNomeContato;
    private java.awt.TextArea EntradaObs;
    private java.awt.TextField EntradaPontoRef;
    private java.awt.TextField EntradaRazao;
    private java.awt.TextField EntradaTelefone1;
    private java.awt.TextField EntradaTelefone2;
    private java.awt.TextField EntradaUF;
    private java.awt.Label Fax;
    private java.awt.Label Fornecedor;
    private java.awt.Label InscricaoEstadual;
    private java.awt.Label NomeContato;
    private java.awt.Label Obs;
    private java.awt.Label PontoRef;
    private java.awt.Label RazaoSocial;
    private javax.swing.JPanel Sair;
    private java.awt.Label Telefone1;
    private java.awt.Label Telefone2;
    private java.awt.Label UF;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
