/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Fornecedor;

import static Conexao_BD.Conexao.stmt;
import Fornecedor.FornecedorInsert;
import static Fornecedor.FornecedorInsert.dados;
import static Fornecedor.FornecedorInsert.rs;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ricardo
 */
public class Alterar_Fornecedor extends javax.swing.JFrame {

    /**
     * Creates new form Alterar_Fornecedor
     */
    private DefaultTableModel Pesquisa;
    private Object[] Linhas;

    public Alterar_Fornecedor() {
        initComponents();
          Pesquisa = new DefaultTableModel(null, new String[]{"NOME_FORNECEDOR",
                 "RAZAO_SOCIAL","NOME_CONTATO","INSCRICAO_ESTADUAL","CNPJ","TELEFONE1"
                 ,"TELEFONE2","FAX","ENDERECO","BAIRRO","CEP","CIDADE","UF","PONTO_REFERENCIA"
                 ,"EMAIL","OBSERVACAO","CODIGO_FORNECEDOR"});
        jTable1.setModel(Pesquisa);
            try {
         rs = stmt.executeQuery("SELECT * FROM FORNECEDOR ");
            while (rs.next()) {

                String N_FORNECEDOR = rs.getString("NOME_FORNECEDOR");
                String R_SOCIAL = rs.getString("RAZAO_SOCIAL");
                String N_CONTATO = rs.getString("NOME_CONTATO");
                String I_ESTADUAL = rs.getString("INSCRICAO_ESTADUAL");
                String CNPJJ = rs.getString("CNPJ");
                String TEL1 = rs.getString("TELEFONE1");
                String TEL2 = rs.getString("TELEFONE2");
                String FAXX = rs.getString("FAX");
                String END = rs.getString("ENDERECO");
                String BAIRROO = rs.getString("BAIRRO");
                String CEPP = rs.getString("CEP");
                String CIDADEE = rs.getString("CIDADE");
                String UFF = rs.getString("UF");
                String P_REFERENCIA = rs.getString("PONTO_REFERENCIA");
                String EMAILL = rs.getString("EMAIL");
                String OBS = rs.getString("OBSERVACAO");
                int C_FORNECEDOR = rs.getInt("CODIGO_FORNECEDOR");
                Linhas = new Object[]{N_FORNECEDOR, 
                    R_SOCIAL,N_CONTATO,I_ESTADUAL,CNPJJ,
                    TEL1,TEL2,FAXX,END,BAIRROO,CEPP,CIDADEE,
                    UFF,P_REFERENCIA,EMAILL,OBS,C_FORNECEDOR};
                Pesquisa.addRow(Linhas);
            }    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " ERRO: " + ex);
        }/*
       DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < FornecedorInsert.dados.size(); i++) {
            dtm.addRow(FornecedorInsert.dados.get(i));
        }*/
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Entrada_Nome_Fornecedor = new javax.swing.JTextField();
        Inf_Fornecedor = new javax.swing.JLabel();
        Pesquisar = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Sair = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Carregar_Tabela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Fornecedor");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Entrada_Nome_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_Nome_FornecedorActionPerformed(evt);
            }
        });

        Inf_Fornecedor.setText("Informe Nome do Fornecedor");

        Pesquisar.setText("Pesquisar");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Entrada_Nome_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Pesquisar))
                    .addComponent(Inf_Fornecedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Inf_Fornecedor)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Entrada_Nome_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo do Fornecedor", "Nome", "Razão Social", "Nome do Contato", "Inscrição Estadual", "CNPJ", "1º Telefone ", "2º Telefone", "FAX", "Endereço", "Bairro", "CEP", "Cidade", "UF", "Ponto de Referência", "E-MAIL", "Observações"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Sair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        Alterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Alterar.setForeground(new java.awt.Color(204, 0, 0));
        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Carregar_Tabela.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Carregar_Tabela.setText("Carregar Tabela");
        Carregar_Tabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carregar_TabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(Alterar)
                .addGap(28, 28, 28)
                .addComponent(Carregar_Tabela)
                .addGap(26, 26, 26)
                .addComponent(Sair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Carregar_Tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed

dispose();        
// TODO add your handling code here:
    }//GEN-LAST:event_SairActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed

        String nome = Entrada_Nome_Fornecedor.getText();
          Pesquisa = new DefaultTableModel(null, new String[]{"NOME_FORNECEDOR",
                 "RAZAO_SOCIAL","NOME_CONTATO","INSCRICAO_ESTADUAL","CNPJ","TELEFONE1"
                 ,"TELEFONE2","FAX","ENDERECO","BAIRRO","CEP","CIDADE","UF","PONTO_REFERENCIA"
                 ,"EMAIL","OBSERVACAO","CODIGO_FORNECEDOR"});
        jTable1.setModel(Pesquisa);
            try {
         rs = stmt.executeQuery("SELECT * FROM FORNECEDOR WHERE NOME_FORNECEDOR = '"+nome+"';");
            while (rs.next()) {

                String N_FORNECEDOR = rs.getString("NOME_FORNECEDOR");
                String R_SOCIAL = rs.getString("RAZAO_SOCIAL");
                String N_CONTATO = rs.getString("NOME_CONTATO");
                String I_ESTADUAL = rs.getString("INSCRICAO_ESTADUAL");
                String CNPJJ = rs.getString("CNPJ");
                String TEL1 = rs.getString("TELEFONE1");
                String TEL2 = rs.getString("TELEFONE2");
                String FAXX = rs.getString("FAX");
                String END = rs.getString("ENDERECO");
                String BAIRROO = rs.getString("BAIRRO");
                String CEPP = rs.getString("CEP");
                String CIDADEE = rs.getString("CIDADE");
                String UFF = rs.getString("UF");
                String P_REFERENCIA = rs.getString("PONTO_REFERENCIA");
                String EMAILL = rs.getString("EMAIL");
                String OBS = rs.getString("OBSERVACAO");
                int C_FORNECEDOR = rs.getInt("CODIGO_FORNECEDOR");
                Linhas = new Object[]{N_FORNECEDOR, 
                    R_SOCIAL,N_CONTATO,I_ESTADUAL,CNPJJ,
                    TEL1,TEL2,FAXX,END,BAIRROO,CEPP,CIDADEE,
                    UFF,P_REFERENCIA,EMAILL,OBS,C_FORNECEDOR};
                Pesquisa.addRow(Linhas);
            }    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " ERRO: " + ex);
        }
    }//GEN-LAST:event_PesquisarActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed

         int LinhaSelecionada = this.jTable1.getSelectedRow();
        String NOME_FORNECEDOR = this.jTable1.getValueAt(LinhaSelecionada, 0).toString();
        String RAZAO_SOCIAL = this.jTable1.getValueAt(LinhaSelecionada, 1).toString();
        String NOME_CONTATO = this.jTable1.getValueAt(LinhaSelecionada, 2).toString();
        String INSCRICAO_ESTADUAL = this.jTable1.getValueAt(LinhaSelecionada, 3).toString();
        String CNPJ = this.jTable1.getValueAt(LinhaSelecionada, 4).toString();
        String TELEFONE_1 = this.jTable1.getValueAt(LinhaSelecionada, 5).toString();
        String TELEFONE_2 = this.jTable1.getValueAt(LinhaSelecionada, 6).toString();
        String FAX = this.jTable1.getValueAt(LinhaSelecionada, 7).toString();
        String ENDERECO = this.jTable1.getValueAt(LinhaSelecionada, 8).toString();
        String BAIRRO = this.jTable1.getValueAt(LinhaSelecionada, 9).toString();
        String CEP = this.jTable1.getValueAt(LinhaSelecionada, 10).toString();
        String CIDADE = this.jTable1.getValueAt(LinhaSelecionada, 11).toString();
        String UF = this.jTable1.getValueAt(LinhaSelecionada, 12).toString();
        String PONTO_REFERENCIA = this.jTable1.getValueAt(LinhaSelecionada, 13).toString();
        String EMAIL = this.jTable1.getValueAt(LinhaSelecionada, 14).toString();
        String OBSERVACAO = this.jTable1.getValueAt(LinhaSelecionada, 15).toString();
        String CODIGO_FORNECEDOR = this.jTable1.getValueAt(LinhaSelecionada, 16). toString();
        
        new Alterar(
                NOME_FORNECEDOR,
                RAZAO_SOCIAL,
                NOME_CONTATO,
                INSCRICAO_ESTADUAL,
                CNPJ,
                TELEFONE_1,
                TELEFONE_2,
                FAX,
                ENDERECO,
                BAIRRO,
                CEP,
                CIDADE,
                UF,
                PONTO_REFERENCIA,
                EMAIL,
                OBSERVACAO,
                CODIGO_FORNECEDOR
                ).setVisible(true);   
    }//GEN-LAST:event_AlterarActionPerformed

    private void Entrada_Nome_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_Nome_FornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entrada_Nome_FornecedorActionPerformed

    private void Carregar_TabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carregar_TabelaActionPerformed
                  Pesquisa = new DefaultTableModel(null, new String[]{"NOME_FORNECEDOR",
                 "RAZAO_SOCIAL","NOME_CONTATO","INSCRICAO_ESTADUAL","CNPJ","TELEFONE1"
                 ,"TELEFONE2","FAX","ENDERECO","BAIRRO","CEP","CIDADE","UF","PONTO_REFERENCIA"
                 ,"EMAIL","OBSERVACAO","CODIGO_FORNECEDOR"});
        jTable1.setModel(Pesquisa);
            try {
         rs = stmt.executeQuery("SELECT * FROM FORNECEDOR ");
            while (rs.next()) {

                String N_FORNECEDOR = rs.getString("NOME_FORNECEDOR");
                String R_SOCIAL = rs.getString("RAZAO_SOCIAL");
                String N_CONTATO = rs.getString("NOME_CONTATO");
                String I_ESTADUAL = rs.getString("INSCRICAO_ESTADUAL");
                String CNPJJ = rs.getString("CNPJ");
                String TEL1 = rs.getString("TELEFONE1");
                String TEL2 = rs.getString("TELEFONE2");
                String FAXX = rs.getString("FAX");
                String END = rs.getString("ENDERECO");
                String BAIRROO = rs.getString("BAIRRO");
                String CEPP = rs.getString("CEP");
                String CIDADEE = rs.getString("CIDADE");
                String UFF = rs.getString("UF");
                String P_REFERENCIA = rs.getString("PONTO_REFERENCIA");
                String EMAILL = rs.getString("EMAIL");
                String OBS = rs.getString("OBSERVACAO");
                int C_FORNECEDOR = rs.getInt("CODIGO_FORNECEDOR");
                Linhas = new Object[]{N_FORNECEDOR, 
                    R_SOCIAL,N_CONTATO,I_ESTADUAL,CNPJJ,
                    TEL1,TEL2,FAXX,END,BAIRROO,CEPP,CIDADEE,
                    UFF,P_REFERENCIA,EMAILL,OBS,C_FORNECEDOR};
                Pesquisa.addRow(Linhas);
            }    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " ERRO: " + ex);
        }
    }//GEN-LAST:event_Carregar_TabelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alterar_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alterar_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alterar_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alterar_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Alterar_Fornecedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Carregar_Tabela;
    private javax.swing.JTextField Entrada_Nome_Fornecedor;
    private javax.swing.JLabel Inf_Fornecedor;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton Sair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
