/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Fornecedor;

import Conexao_BD.Conexao;
import static Conexao_BD.Conexao.stmt;
import static Fornecedor.FornecedorInsert.rs;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ricardo
 */
public class Excluir_Fornecedor extends javax.swing.JFrame {

    /**
     * Creates new form Excluir_Fornecedor
     */
    
    private DefaultTableModel Pesquisa;
    private Object[] Linhas;
    Statement stmt = Conexao.stmt;

    public Excluir_Fornecedor() {
        initComponents();
        Pesquisa = new DefaultTableModel(null, new String[]{"NOME_FORNECEDOR",
                 "RAZAO_SOCIAL","NOME_CONTATO","INSCRICAO_ESTADUAL","CNPJ","TELEFONE1"
                 ,"TELEFONE2","FAX","ENDERECO","BAIRRO","CEP","CIDADE","UF","PONTO_REFERENCIA"
                 ,"EMAIL","OBSERVACAO","CODIGO_FORNECEDOR"});
        jTable1.setModel(Pesquisa);
            try {
         rs = stmt.executeQuery("SELECT * FROM FORNECEDOR ");
            while (rs.next()) {

                String N_FORNECEDOR = rs.getString("NOME_FORNECEDOR");
                String R_SOCIAL = rs.getString("RAZAO_SOCIAL");
                String N_CONTATO = rs.getString("NOME_CONTATO");
                String I_ESTADUAL = rs.getString("INSCRICAO_ESTADUAL");
                String CNPJJ = rs.getString("CNPJ");
                String TEL1 = rs.getString("TELEFONE1");
                String TEL2 = rs.getString("TELEFONE2");
                String FAXX = rs.getString("FAX");
                String END = rs.getString("ENDERECO");
                String BAIRROO = rs.getString("BAIRRO");
                String CEPP = rs.getString("CEP");
                String CIDADEE = rs.getString("CIDADE");
                String UFF = rs.getString("UF");
                String P_REFERENCIA = rs.getString("PONTO_REFERENCIA");
                String EMAILL = rs.getString("EMAIL");
                String OBS = rs.getString("OBSERVACAO");
                int C_FORNECEDOR = rs.getInt("CODIGO_FORNECEDOR");
                Linhas = new Object[]{N_FORNECEDOR, 
                    R_SOCIAL,N_CONTATO,I_ESTADUAL,CNPJJ,
                    TEL1,TEL2,FAXX,END,BAIRROO,CEPP,CIDADEE,
                    UFF,P_REFERENCIA,EMAILL,OBS,C_FORNECEDOR};
                Pesquisa.addRow(Linhas);
            }    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " ERRO: " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ntradaNome = new javax.swing.JTextField();
        Info_CentroCusto = new javax.swing.JLabel();
        Ok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Entrada_Nome_Fornecedor = new javax.swing.JTextField();
        Inf_Fornecedor = new javax.swing.JLabel();
        Pesquisar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Excluir = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CarregarTabela = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Info_CentroCusto.setText("Informe Nome do Fornecedor");

        Ok.setText("Ok");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Info_CentroCusto)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ntradaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ok)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Info_CentroCusto)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ntradaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ok))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Excluir Fornecedor");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Inf_Fornecedor.setText("Informe Nome do Fornecedor");

        Pesquisar.setText("Pesquisar");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inf_Fornecedor)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Entrada_Nome_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Pesquisar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(Inf_Fornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Entrada_Nome_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Razão Social", "Nome do Contato", "Inscrição Estadual", "CNPJ", "1º Telefone ", "2º Telefone", "FAX", "Endereço", "Bairro", "CEP", "Cidade", "UF", "Ponto de Referência", "E-MAIL", "Observações", "Codigo do Fornecedor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        CarregarTabela.setText("Carregar Tabela");
        CarregarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarTabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(384, Short.MAX_VALUE)
                .addComponent(Excluir)
                .addGap(27, 27, 27)
                .addComponent(CarregarTabela)
                .addGap(24, 24, 24)
                .addComponent(Sair)
                .addGap(372, 372, 372))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(CarregarTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed

dispose();        
// TODO add your handling code here:
    }//GEN-LAST:event_SairActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
       
        
        String nome = Entrada_Nome_Fornecedor.getText();
          Pesquisa = new DefaultTableModel(null, new String[]{"NOME_FORNECEDOR",
                 "RAZAO_SOCIAL","NOME_CONTATO","INSCRICAO_ESTADUAL","CNPJ","TELEFONE1"
                 ,"TELEFONE2","FAX","ENDERECO","BAIRRO","CEP","CIDADE","UF","PONTO_REFERENCIA"
                 ,"EMAIL","OBSERVACAO","CODIGO_FORNECEDOR"});
        jTable1.setModel(Pesquisa);
            try {
         rs = stmt.executeQuery("SELECT * FROM FORNECEDOR WHERE NOME_FORNECEDOR = '"+nome+"';");
            while (rs.next()) {

                String N_FORNECEDOR = rs.getString("NOME_FORNECEDOR");
                String R_SOCIAL = rs.getString("RAZAO_SOCIAL");
                String N_CONTATO = rs.getString("NOME_CONTATO");
                String I_ESTADUAL = rs.getString("INSCRICAO_ESTADUAL");
                String CNPJJ = rs.getString("CNPJ");
                String TEL1 = rs.getString("TELEFONE1");
                String TEL2 = rs.getString("TELEFONE2");
                String FAXX = rs.getString("FAX");
                String END = rs.getString("ENDERECO");
                String BAIRROO = rs.getString("BAIRRO");
                String CEPP = rs.getString("CEP");
                String CIDADEE = rs.getString("CIDADE");
                String UFF = rs.getString("UF");
                String P_REFERENCIA = rs.getString("PONTO_REFERENCIA");
                String EMAILL = rs.getString("EMAIL");
                String OBS = rs.getString("OBSERVACAO");
                int C_FORNECEDOR = rs.getInt("CODIGO_FORNECEDOR");
                Linhas = new Object[]{N_FORNECEDOR, 
                    R_SOCIAL,N_CONTATO,I_ESTADUAL,CNPJJ,
                    TEL1,TEL2,FAXX,END,BAIRROO,CEPP,CIDADEE,
                    UFF,P_REFERENCIA,EMAILL,OBS,C_FORNECEDOR};
                Pesquisa.addRow(Linhas);
            }    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " ERRO: " + ex);
        }
        
    }//GEN-LAST:event_PesquisarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
    
        int LinhaSelecionada = this.jTable1.getSelectedRow();
        String NOME_FORNECEDOR = this.jTable1.getValueAt(LinhaSelecionada, 0).toString();
        String RAZAO_SOCIAL = this.jTable1.getValueAt(LinhaSelecionada, 1).toString();
        String NOME_CONTATO = this.jTable1.getValueAt(LinhaSelecionada, 2).toString();
        String INSCRICAO_ESTADUAL = this.jTable1.getValueAt(LinhaSelecionada, 3).toString();
        String CNPJ = this.jTable1.getValueAt(LinhaSelecionada, 4).toString();
        String TELEFONE_1 = this.jTable1.getValueAt(LinhaSelecionada, 5).toString();
        String TELEFONE_2 = this.jTable1.getValueAt(LinhaSelecionada, 6).toString();
        String FAX = this.jTable1.getValueAt(LinhaSelecionada, 7).toString();
        String ENDERECO = this.jTable1.getValueAt(LinhaSelecionada, 8).toString();
        String BAIRRO = this.jTable1.getValueAt(LinhaSelecionada, 9).toString();
        String CEP = this.jTable1.getValueAt(LinhaSelecionada, 10).toString();
        String CIDADE = this.jTable1.getValueAt(LinhaSelecionada, 11).toString();
        String UF = this.jTable1.getValueAt(LinhaSelecionada, 12).toString();
        String PONTO_REFERENCIA = this.jTable1.getValueAt(LinhaSelecionada, 13).toString();
        String EMAIL = this.jTable1.getValueAt(LinhaSelecionada, 14).toString();
        String OBSERVACAO = this.jTable1.getValueAt(LinhaSelecionada, 15).toString();
        String CODIGO_FORNECEDOR = this.jTable1.getValueAt(LinhaSelecionada, 16). toString();
        
        int x = JOptionPane.showConfirmDialog(null, "Deseja Realmente Excluir esse item?");

        if (x == JOptionPane.OK_OPTION) {
            try {
                 
                stmt.executeUpdate("DELETE FROM FORNECEDOR WHERE CODIGO_FORNECEDOR = '" + CODIGO_FORNECEDOR + "' ");
                JOptionPane.showMessageDialog(null, " Deletado com Sucesso!");

            } catch (java.sql.SQLException e) {
                JOptionPane.showMessageDialog(null, " Erro ao Deletar Grupo!");
            }
        } else {

            JOptionPane.showMessageDialog(null, "Grupo não Excluido! ");
            FornecedorInsert.rs = null;
        }
        
    }//GEN-LAST:event_ExcluirActionPerformed

    private void CarregarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregarTabelaActionPerformed
        
        
        Pesquisa = new DefaultTableModel(null, new String[]{"NOME_FORNECEDOR",
                 "RAZAO_SOCIAL","NOME_CONTATO","INSCRICAO_ESTADUAL","CNPJ","TELEFONE1"
                 ,"TELEFONE2","FAX","ENDERECO","BAIRRO","CEP","CIDADE","UF","PONTO_REFERENCIA"
                 ,"EMAIL","OBSERVACAO","CODIGO_FORNECEDOR"});
        jTable1.setModel(Pesquisa);
            try {
         rs = stmt.executeQuery("SELECT * FROM FORNECEDOR ");
            while (rs.next()) {

                String N_FORNECEDOR = rs.getString("NOME_FORNECEDOR");
                String R_SOCIAL = rs.getString("RAZAO_SOCIAL");
                String N_CONTATO = rs.getString("NOME_CONTATO");
                String I_ESTADUAL = rs.getString("INSCRICAO_ESTADUAL");
                String CNPJJ = rs.getString("CNPJ");
                String TEL1 = rs.getString("TELEFONE1");
                String TEL2 = rs.getString("TELEFONE2");
                String FAXX = rs.getString("FAX");
                String END = rs.getString("ENDERECO");
                String BAIRROO = rs.getString("BAIRRO");
                String CEPP = rs.getString("CEP");
                String CIDADEE = rs.getString("CIDADE");
                String UFF = rs.getString("UF");
                String P_REFERENCIA = rs.getString("PONTO_REFERENCIA");
                String EMAILL = rs.getString("EMAIL");
                String OBS = rs.getString("OBSERVACAO");
                int C_FORNECEDOR = rs.getInt("CODIGO_FORNECEDOR");
                Linhas = new Object[]{N_FORNECEDOR, 
                    R_SOCIAL,N_CONTATO,I_ESTADUAL,CNPJJ,
                    TEL1,TEL2,FAXX,END,BAIRROO,CEPP,CIDADEE,
                    UFF,P_REFERENCIA,EMAILL,OBS,C_FORNECEDOR};
                Pesquisa.addRow(Linhas);
            }    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " ERRO: " + ex);
        }
        
    }//GEN-LAST:event_CarregarTabelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Excluir_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Excluir_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Excluir_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Excluir_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Excluir_Fornecedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CarregarTabela;
    private javax.swing.JTextField Entrada_Nome_Fornecedor;
    private javax.swing.JButton Excluir;
    private javax.swing.JLabel Inf_Fornecedor;
    private javax.swing.JLabel Info_CentroCusto;
    private javax.swing.JButton Ok;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton Sair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ntradaNome;
    // End of variables declaration//GEN-END:variables
}
