/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Relatorios;

import static Conexao_BD.Conexao.stmt;
import static Fornecedor.FornecedorInsert.rs;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ricardo
 */
public class Relacao_Fornecedor extends javax.swing.JFrame {

    /**
     * Creates new form Relacao_Fornecedor
     */
     private DefaultTableModel Pesquisa;
    private Object[] Linhas;

    public Relacao_Fornecedor() {
        initComponents();
        
         Pesquisa = new DefaultTableModel(null, new String[]{"NOME_FORNECEDOR",
                 "RAZAO_SOCIAL","NOME_CONTATO","INSCRICAO_ESTADUAL","CNPJ","TELEFONE1"
                 ,"TELEFONE2","FAX","ENDERECO","BAIRRO","CEP","CIDADE","UF","PONTO_REFERENCIA"
                 ,"EMAIL","OBSERVACAO","CODIGO_FORNECEDOR"});
        jTable1.setModel(Pesquisa);
            try {
         rs = stmt.executeQuery("SELECT * FROM FORNECEDOR ");
            while (rs.next()) {

                String N_FORNECEDOR = rs.getString("NOME_FORNECEDOR");
                String R_SOCIAL = rs.getString("RAZAO_SOCIAL");
                String N_CONTATO = rs.getString("NOME_CONTATO");
                String I_ESTADUAL = rs.getString("INSCRICAO_ESTADUAL");
                String CNPJJ = rs.getString("CNPJ");
                String TEL1 = rs.getString("TELEFONE1");
                String TEL2 = rs.getString("TELEFONE2");
                String FAXX = rs.getString("FAX");
                String END = rs.getString("ENDERECO");
                String BAIRROO = rs.getString("BAIRRO");
                String CEPP = rs.getString("CEP");
                String CIDADEE = rs.getString("CIDADE");
                String UFF = rs.getString("UF");
                String P_REFERENCIA = rs.getString("PONTO_REFERENCIA");
                String EMAILL = rs.getString("EMAIL");
                String OBS = rs.getString("OBSERVACAO");
                int C_FORNECEDOR = rs.getInt("CODIGO_FORNECEDOR");
                Linhas = new Object[]{N_FORNECEDOR, 
                    R_SOCIAL,N_CONTATO,I_ESTADUAL,CNPJJ,
                    TEL1,TEL2,FAXX,END,BAIRROO,CEPP,CIDADEE,
                    UFF,P_REFERENCIA,EMAILL,OBS,C_FORNECEDOR};
                Pesquisa.addRow(Linhas);
            }    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " ERRO: " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Carregar_Tabela = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relação de Fornecedores");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo do Fornecedor", "Nome", "Razão Social", "Nome do Contato", "Inscrição Estadual", "CNPJ", "1º Telefone ", "2º Telefone", "FAX", "Endereço", "Bairro", "CEP", "Cidade", "UF", "Ponto de Referência", "E-MAIL", "Observações"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Carregar_Tabela.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Carregar_Tabela.setText("Atualizar");
        Carregar_Tabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carregar_TabelaActionPerformed(evt);
            }
        });

        Sair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("FORNECEDORES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(433, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Carregar_Tabela)
                        .addGap(28, 28, 28)
                        .addComponent(Sair)
                        .addGap(426, 426, 426))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(428, 428, 428))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Carregar_Tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Carregar_TabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carregar_TabelaActionPerformed
        Pesquisa = new DefaultTableModel(null, new String[]{"NOME_FORNECEDOR",
            "RAZAO_SOCIAL","NOME_CONTATO","INSCRICAO_ESTADUAL","CNPJ","TELEFONE1"
            ,"TELEFONE2","FAX","ENDERECO","BAIRRO","CEP","CIDADE","UF","PONTO_REFERENCIA"
            ,"EMAIL","OBSERVACAO","CODIGO_FORNECEDOR"});
    jTable1.setModel(Pesquisa);
    try {
        rs = stmt.executeQuery("SELECT * FROM FORNECEDOR ");
        while (rs.next()) {

            String N_FORNECEDOR = rs.getString("NOME_FORNECEDOR");
            String R_SOCIAL = rs.getString("RAZAO_SOCIAL");
            String N_CONTATO = rs.getString("NOME_CONTATO");
            String I_ESTADUAL = rs.getString("INSCRICAO_ESTADUAL");
            String CNPJJ = rs.getString("CNPJ");
            String TEL1 = rs.getString("TELEFONE1");
            String TEL2 = rs.getString("TELEFONE2");
            String FAXX = rs.getString("FAX");
            String END = rs.getString("ENDERECO");
            String BAIRROO = rs.getString("BAIRRO");
            String CEPP = rs.getString("CEP");
            String CIDADEE = rs.getString("CIDADE");
            String UFF = rs.getString("UF");
            String P_REFERENCIA = rs.getString("PONTO_REFERENCIA");
            String EMAILL = rs.getString("EMAIL");
            String OBS = rs.getString("OBSERVACAO");
            int C_FORNECEDOR = rs.getInt("CODIGO_FORNECEDOR");
            Linhas = new Object[]{N_FORNECEDOR,
                R_SOCIAL,N_CONTATO,I_ESTADUAL,CNPJJ,
                TEL1,TEL2,FAXX,END,BAIRROO,CEPP,CIDADEE,
                UFF,P_REFERENCIA,EMAILL,OBS,C_FORNECEDOR};
            Pesquisa.addRow(Linhas);
        }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " ERRO: " + ex);
        }
    }//GEN-LAST:event_Carregar_TabelaActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relacao_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relacao_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relacao_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relacao_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relacao_Fornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carregar_Tabela;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
